title: 云吞铺子

author: 小云吞

menus: 
  关于: /about

links:
  github: https://github.com/spaceack
  
favicon: /favicon.ico

# valine 
valine:
    # 评论
    enableComment: false
    # 阅读量
    enableCounter: true
    # valine appID
    appID: 
    # valine appKey
    appKey: 
    placeholder: 请输入评论
    avatar: retro

# 是否开启“不蒜子”统计访问量
busuanzi: true

# 底部版权开始年份
siteStartYear: 2014